### ISSUE TITLE
pygame.error EGL not initialized

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#70]
I did an upgrade of my Pi400 to bookworm and now get this  error when I run dashboard.py Was this the error associated with the later modules you have in the DEV branch?

```
pi@n1mmview:~/n1mm_view $ sudo ./dashboard.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-12-30 19:08:41.956 INFO     [config::__init__] Setting log level to WARN
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
MESA-LOADER: failed to open vc4: /usr/lib/dri/vc4_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: vc4
MESA-LOADER: failed to open zink: /usr/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: zink
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
2024-12-30 19:08:44.392 ERROR    [dashboard::main] Could not initialize display.
Traceback (most recent call last):
  File "/home/pi/n1mm_view/./dashboard.py", line 326, in main
    screen, size = graphics.init_display()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/n1mm_view/graphics.py", line 82, in init_display
    screen = pygame.display.set_mode(size, pygame.FULLSCREEN)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pygame.error: EGL not initialized
pi@n1mmview:~/n1mm_view $
```

**Comment by n1kdo** [comment]
No. The changes I made were for the latest matplotlib.

X11 or Wayland or no graphics?

I have a Pi 3B that I ran on Field Day last year, let me give it a shot.

**Comment by ny4i** [comment]
No graphics. I use the lite OS.

**Comment by n1kdo** [comment]
working here.  runs in Wayland, did not try X11, this is raw console (no
GUI.)

```
***@***.***:~/n1mm_view $ uname -a
Linux raspberrypi3 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1
(2024-11-25) aarch64 GNU/Linux
***@***.***:~/n1mm_view $ cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
***@***.***:~/n1mm_view $ ./dashboard.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-12-30 22:21:49.296 INFO     [config::__init__] Setting log level to
INFO
2024-12-30 22:21:49.297 INFO     [config::__init__] Reading config file @
['/home/jeff/n1mm_view/n1mm_view.ini']
2024-12-30 22:21:49.297 INFO     [config::__init__] Using database file
n1mm_view.db
2024-12-30 22:21:49.298 INFO     [config::__init__] Using logo file logo.png
2024-12-30 22:21:49.310 INFO     [config::__init__] LIstening on UDP port
12060
2024-12-30 22:21:49.314 INFO     [constants::<module>] Starting constants.py
2024-12-30 22:21:52.865 INFO     [dashboard::main] dashboard startup
2024-12-30 22:21:53.110 INFO     [graphics::init_display] Discovered
compatible driver kmsdrm
2024-12-30 22:21:53.541 INFO     [graphics::init_display] display size:
1920 x 1080
```

**Comment by n1kdo** [comment]
also works in X11.

Jeff

**Comment by ny4i** [comment]
Ok. Let me dig into it a bit more. 

I see on your system it found the driver kmsdrm so I’ll start there. 

Thanks 

Tom
Principal Solutions Architect
Better Software Solutions, Inc. 
727-437-2771
813-205-6388 (mobile/text)

**Comment by ny4i** [comment]
I finally got back to this...I just did a completely fresh install of bookwork on a pi400.

Same error...

By any chance, the version you ran it on OK was that the one your were working on for the dependencies?

My nest option will probably be to go back to bullseye.

```
pi@pi400:~/n1mm_view$ ./dashboard.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
2025-01-07 08:54:15.448 INFO     [config::__init__] Setting log level to DEBUG
2025-01-07 08:54:15.448 INFO     [config::__init__] Reading config file @ ['/home/pi/.config/n1mm_view.ini']
2025-01-07 08:54:15.448 INFO     [config::__init__] Using database file n1mm_view.db
2025-01-07 08:54:15.449 ERROR    [config::__init__] Logo file /home/pi/wfda_logo.png does not exist
2025-01-07 08:54:15.455 INFO     [config::__init__] LIstening on UDP port 12060
2025-01-07 08:54:15.466 INFO     [constants::<module>] Starting constants.py
2025-01-07 08:54:15.505 DEBUG    [geos::load_dll] Trying `CDLL(libgeos_c.so.1)`
2025-01-07 08:54:15.510 DEBUG    [geos::load_dll] Library path: 'libgeos_c.so.1'
2025-01-07 08:54:15.511 DEBUG    [geos::load_dll] DLL: <CDLL 'libgeos_c.so.1', handle 1aa9ae40 at 0x7f97517010>
2025-01-07 08:54:15.914 DEBUG    [__init__::wrapper] matplotlib data path: /usr/share/matplotlib/mpl-data
2025-01-07 08:54:15.925 DEBUG    [__init__::wrapper] CONFIGDIR=/home/pi/.config/matplotlib
2025-01-07 08:54:15.928 DEBUG    [__init__::<module>] interactive is False
2025-01-07 08:54:15.928 DEBUG    [__init__::<module>] platform is linux
2025-01-07 08:54:16.013 DEBUG    [__init__::wrapper] CACHEDIR=/home/pi/.cache/matplotlib
2025-01-07 08:54:16.014 DEBUG    [font_manager::__init__] font search path [PosixPath('/usr/share/matplotlib/mpl-data/fonts/ttf'), PosixPath('/usr/share/matplotlib/mpl-data/fonts/afm'), PosixPath('/usr/share/matplotlib/mpl-data/fonts/pdfcorefonts')]
2025-01-07 08:54:16.487 INFO     [font_manager::_load_fontmanager] generated new fontManager
2025-01-07 08:54:17.363 INFO     [dashboard::main] dashboard startup
2025-01-07 08:54:17.400 DEBUG    [graphics::init_display] pygame error x11 not available
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] Driver: x11 failed.
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] pygame error dga not available
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] Driver: dga failed.
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] pygame error fbcon not available
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] Driver: fbcon failed.
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] pygame error directfb not available
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] Driver: directfb failed.
2025-01-07 08:54:17.401 DEBUG    [graphics::init_display] pygame error svgalib not available
2025-01-07 08:54:17.402 DEBUG    [graphics::init_display] Driver: svgalib failed.
2025-01-07 08:54:17.402 DEBUG    [graphics::init_display] pygame error ggi not available
2025-01-07 08:54:17.402 DEBUG    [graphics::init_display] Driver: ggi failed.
2025-01-07 08:54:17.402 DEBUG    [graphics::init_display] pygame error wayland not available
2025-01-07 08:54:17.402 DEBUG    [graphics::init_display] Driver: wayland failed.
2025-01-07 08:54:17.615 INFO     [graphics::init_display] Discovered compatible driver kmsdrm
MESA-LOADER: failed to open vc4: /usr/lib/dri/vc4_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open zink: /usr/lib/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
2025-01-07 08:54:17.661 ERROR    [dashboard::main] Could not initialize display.
Traceback (most recent call last):
  File "/home/pi/n1mm_view/./dashboard.py", line 326, in main
    screen, size = graphics.init_display()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/n1mm_view/graphics.py", line 82, in init_display
    screen = pygame.display.set_mode(size, pygame.FULLSCREEN)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pygame.error: EGL not initialized
pi@pi400:~/n1mm_view$
```

**Comment by n1kdo** [comment]
Hi Tom,

I did not update the dependencies when I tested on my Pi 4.  The dependency in question is Matplotlib, this problem is coming from PyGame.  Google does return some hits for the MESA-LOADER errors, it looks like missing dependencies for Bookworm.  I have the GUI installed on my test system FWIW.  Are you able to start and run X11 or Wayland?

We can take this to direct email if that is faster.  my call sign at my call sign dot com...

**Comment by n1kdo** [comment]
Can this issue be closed?  I believe everything works on the latest debian bookworm...

**Comment by ny4i** [comment]
Yes it can. Thanks
